[versions]

activityCompose = "1.12.4"
androidTest = "1.3.0"
appcompat = "1.7.1"
compose = "1.3.1"
composeBoom = "2026.02.00"
composeConstraintLayout = "1.1.1"
composeMaterial = "1.3.1"
composeNavigation= "2.9.7"
composeZoomable= "0.3.0"
core = "1.17.0"
coroutines = "1.10.2"
detekt = "1.23.8"
detektCompose = "0.5.6"
espresso = "3.7.0"
junit = "4.13.2"
junit5 = "6.0.3"
koin = "4.1.1"
ktor = "3.4.0"
lifecycle = "2.10.0"
moshi = "1.15.2"
okhttp = "5.3.2"
retrofit = "3.0.0"
room = "2.8.4"
window="1.5.1"
agp = "8.13.2"
kotlin = "2.3.10"
material = "1.13.0"
ksp = "2.3.5"

[libraries]

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }
androidx-window-core = { group = "androidx.window", name = "window-core", version.ref = "window" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBoom" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-runtime-liveData = { module = "androidx.compose.runtime:runtime-livedata" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-util = { module = "androidx.compose.ui:ui-util" }

detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }

injection-koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
injection-koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
injection-koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

squareup-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
squareup-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
squareup-moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
squareup-moshi-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
squareup-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref= "okhttp" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidTest" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "espresso" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
squareup-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]

android = [
    "androidx-core",
    "androidx-appcompat",
    "androidx-lifecycle-viewmodel",
    "androidx-lifecycle-viewmodel-compose"
]

compose = [
    "compose-activity",
    "compose-constraintlayout",
    "compose-foundation",
    "compose-foundation-layout",
    "compose-material",
    "compose-material-icons",
    "compose-material-icons-extended",
    "compose-material3",
    "compose-navigation",
    "compose-runtime",
    "compose-runtime-liveData",
    "compose-ui",
    "compose-ui-tooling",
    "compose-ui-tooling-preview",
    "compose-util",
    "androidx-window-core"
]

detekt = [
    "detekt-api",
    "detekt-compose",
    "detekt-formatting",
    "detekt-test"
]

injection = [
    "injection-koin-core",
    "injection-koin-android",
    "injection-koin-android-compose"
]

retrofit = [
    "squareup-moshi",
    "squareup-moshi-kotlin",
    "squareup-moshi-codegen",
    "squareup-moshi-converter",
    "squareup-logging-interceptor",
    "squareup-okhttp",
    "squareup-retrofit"
]

ktor = [
    "ktor-auth",
    "ktor-content-negotiation",
    "ktor-core",
    "ktor-json",
    "ktor-logging",
    "ktor-okhttp"
]

room = [
    "androidx-room-ktx",
    "androidx-room-compiler",
    "androidx-room-runtime"
]

androidTest = [
    "androidx-junit",
    "androidx-espresso-core"
]

test = [
    "junit-jupiter",
    "junit-vintage-engine",
    "squareup-mockwebserver",
    "kotlin-coroutines-test"
]
